python main.py \
--image_dir ../R2Gen-wrong/data/iu_xray/images/ \
--ann_path ../R2Gen-wrong/data/iu_xray/new_annotation.json \
--dataset_name iu_xray \
--max_seq_length 60 \
--threshold 3 \
--batch_size 8 \
--epochs 100 \
--save_dir results/iu_xray \
--step_size 50 \
--gamma 0.1 \
--seed 9223 \
--resume results/iu_xray/model_best.pth
